### ISSUE TITLE
train_data is 288, val_data is 0, test_data is 0

### ISSUE THREAD

**Issue by deng1604** [mk-runner/FSE#3]
作者您好，我在运行`bash pretrain_mimic_cxr.sh`文件时，出现了这个错误：
```
train_data is 288, val_data is 0, test_data is 0
Some weights of BertModel were not initialized from the model checkpoint at /home/deng/Desktop/FSE/checkpoints/scibert_scivocab_uncased and are newly initialized because the shapes did not match:
- bert.embeddings.word_embeddings.weight: found shape torch.Size([31090, 768]) in the checkpoint and torch.Size([9841, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
finish instantiate model!, Trainable parameters: 148.270656M
start pretrain!
Epoch 1, step 0/9, itc instance loss: 3.457, itc region loss: 4.078, all_loss: 7.535, lr: 5e-05
Epoch 1, step 8/9, itc instance loss: 3.477, itc region loss: 3.638, all_loss: 7.115, lr: 5e-05
Traceback (most recent call last):
  File "/home/deng/Desktop/FSE/main_finetune.py", line 223, in <module>
    main()
  File "/home/deng/Desktop/FSE/main_finetune.py", line 201, in main
    trainer.train()
  File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 68, in train
    result = self._train_epoch(epoch)
  File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in _train_epoch
    val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
  File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in <dictcomp>
    val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
ZeroDivisionError: float division by zero
```

很奇怪，我看到这个测试集和验证集的长度都是0。
我想，原因是，我生成的 `mimic_cxr_annotation_sen.json` 文件中，在val、test部分，有些的`core_findings`是空的，例如：
```
{
  "train": [
    {
      # 训练集的某一个，其 core_findings 不为空
      "id": "02aa804e-bde0afdd-112c0b34-7bc16630-4e384014",
      "study_id": 50414267,
      "subject_id": 10000032,
      "report": "There is no focal consolidation , pleural effusion or pneumothorax . Bilateral nodular opacities that most likely represent nipple shadows . The cardiomediastinal silhouette is normal . Clips project over the left lung , potentially within the breast . The imaged upper abdomen is unremarkable . Chronic deformity of the posterior left sixth and seventh ribs are noted .",
      "image_path": [
        "p10/p10000032/s50414267/02aa804e-bde0afdd-112c0b34-7bc16630-4e384014.jpg"
      ],
      "core_findings": [
        "no focal consolidation pleural effusion pneumothorax",
        "Bilateral nodular opacities nipple shadows",
        "cardiomediastinal silhouette normal",
        "Clips left lung breast",
        "upper abdomen unremarkable",
        "Chronic deformity posterior left sixth seventh ribs"
      ]
    },



# 下面的这个是测试集的某一个
{
      "id": "d122eb74-bc404dd2-45a05cd3-18505b72-5058fbdd",
      "study_id": 59381316,
      "subject_id": 19991135,
      "report": "PA and lateral chest views were obtained with patient in upright  position .   Comparison is made with the next preceding similar study obtained  four hours earlier during the same day .   The previously described right-sided  chest tube remains in unchanged position .   No pneumothorax has developed and  there is no evidence of significantly increased pleural densities during this  interval .   The right-sided chest wall emphysema described earlier has  regressed .   No new abnormalities are seen .   Left-sided hemithorax is  unremarkable . ",
      "image_path": [
        "p19/p19991135/s59381316/d122eb74-bc404dd2-45a05cd3-18505b72-5058fbdd.jpg"
      ],
      "core_findings": []
    }
```

然后，在文件`datasets_two_step.py`中，
```python
class PretrainBaseDataset(Dataset):  # finetune and inference phase
    def __init__(self, args, tokenizer, split, transform=None):
        self.image_dir = args['image_dir']
        self.transform = transform
        self.tokenizer = tokenizer
        ann = json.loads(open(args['ann_path'], 'r').read())
        ann = ann[split]
        self.examples = []
        self.max_seq_length = args['max_seq_len']
        if args['align_type'] == 'keywords':
            for i in range(len(ann)):
                if len(ann[i]['core_findings']) == 0:  # 这个跳过了
                    continue
                core_findings = ann[i]['core_findings']
                if args['tokenizer_type'] == 'uncased':
                    core_findings = list(map(lambda x: str(x).lower(), core_findings))
                if args['data_name'] == 'mimic_cxr':
                    item_id = '_'.join([str(ann[i]['subject_id']), str(ann[i]['study_id']), ann[i]['id']])
                else:
                    item_id = ann[i]['id']
                self.examples.append({
                    # "report": report.strip(),
                    'image_path': ann[i]['image_path'],
                    'radgraph': ' [SEP] '.join(core_findings),
                    'id': item_id
                })
        ...........


    def __len__(self):
        return len(self.examples)

```
是我前面的生成不对吗？

**Comment by deng1604** [comment]
我配置的 conda 环境，是您提供的那个，应该是没有什么问题的。
我又重新运行了**两次** `knowledge_encoder/factual_serialization.py`文件，这次，在运行`bash pretrain_mimic_cxr.sh`时，出现的是：
```
train_data is 269239, val_data is 0, test_data is 0


Some weights of BertModel were not initialized from the model checkpoint at /home/deng/Desktop/FSE/checkpoints/scibert_scivocab_uncased and are newly initialized because the shapes did not match:
- bert.embeddings.word_embeddings.weight: found shape torch.Size([31090, 768]) in the checkpoint and torch.Size([9841, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
finish instantiate model!, Trainable parameters: 148.270656M
start pretrain!
Epoch 1, step 0/8414, itc instance loss: 3.457, itc region loss: 4.078, all_loss: 7.535, lr: 5e-05
Epoch 1, step 1000/8414, itc instance loss: 2.698, itc region loss: 3.558, all_loss: 6.256, lr: 5e-05
Epoch 1, step 2000/8414, itc instance loss: 3.218, itc region loss: 3.625, all_loss: 6.843, lr: 5e-05
Epoch 1, step 3000/8414, itc instance loss: 2.838, itc region loss: 2.816, all_loss: 5.654, lr: 5e-05
Epoch 1, step 4000/8414, itc instance loss: 2.799, itc region loss: 2.925, all_loss: 5.724, lr: 5e-05
Epoch 1, step 5000/8414, itc instance loss: 3.264, itc region loss: 2.646, all_loss: 5.911, lr: 5e-05
Epoch 1, step 6000/8414, itc instance loss: 2.855, itc region loss: 3.199, all_loss: 6.054, lr: 5e-05
Epoch 1, step 7000/8414, itc instance loss: 2.491, itc region loss: 2.732, all_loss: 5.224, lr: 5e-05
Epoch 1, step 8000/8414, itc instance loss: 2.839, itc region loss: 2.509, all_loss: 5.348, lr: 5e-05
Epoch 1, step 8413/8414, itc instance loss: 2.457, itc region loss: 2.716, all_loss: 5.173, lr: 5e-05
Epoch 1, all train_loss: 5.891088151410381, lr: 5e-05
Traceback (most recent call last):
  File "/home/deng/Desktop/FSE/main_finetune.py", line 223, in <module>
    main()
  File "/home/deng/Desktop/FSE/main_finetune.py", line 201, in main
    trainer.train()
  File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 68, in train
    result = self._train_epoch(epoch)
  File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in _train_epoch
    val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
  File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in <dictcomp>
    val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
ZeroDivisionError: float division by zero
```

为什么在`mimic_cxr_annotation_sen.json`文件中，`test`、`val`部分，生成的`core_findings` 是空列表呢？

**Comment by mk-runner** [comment]
> 作者您好，我在运行`bash pretrain_mimic_cxr.sh`文件时，出现了这个错误：
> 
> ```
> train_data is 288, val_data is 0, test_data is 0
> Some weights of BertModel were not initialized from the model checkpoint at /home/deng/Desktop/FSE/checkpoints/scibert_scivocab_uncased and are newly initialized because the shapes did not match:
> - bert.embeddings.word_embeddings.weight: found shape torch.Size([31090, 768]) in the checkpoint and torch.Size([9841, 768]) in the model instantiated
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> finish instantiate model!, Trainable parameters: 148.270656M
> start pretrain!
> Epoch 1, step 0/9, itc instance loss: 3.457, itc region loss: 4.078, all_loss: 7.535, lr: 5e-05
> Epoch 1, step 8/9, itc instance loss: 3.477, itc region loss: 3.638, all_loss: 7.115, lr: 5e-05
> Traceback (most recent call last):
>   File "/home/deng/Desktop/FSE/main_finetune.py", line 223, in <module>
>     main()
>   File "/home/deng/Desktop/FSE/main_finetune.py", line 201, in main
>     trainer.train()
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 68, in train
>     result = self._train_epoch(epoch)
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in _train_epoch
>     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in <dictcomp>
>     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
> ZeroDivisionError: float division by zero
> ```
> 
> 很奇怪，我看到这个测试集和验证集的长度都是0。 我想，原因是，我生成的 `mimic_cxr_annotation_sen.json` 文件中，在val、test部分，有些的`core_findings`是空的，例如：
> 
> ```
> {
>   "train": [
>     {
>       # 训练集的某一个，其 core_findings 不为空
>       "id": "02aa804e-bde0afdd-112c0b34-7bc16630-4e384014",
>       "study_id": 50414267,
>       "subject_id": 10000032,
>       "report": "There is no focal consolidation , pleural effusion or pneumothorax . Bilateral nodular opacities that most likely represent nipple shadows . The cardiomediastinal silhouette is normal . Clips project over the left lung , potentially within the breast . The imaged upper abdomen is unremarkable . Chronic deformity of the posterior left sixth and seventh ribs are noted .",
>       "image_path": [
>         "p10/p10000032/s50414267/02aa804e-bde0afdd-112c0b34-7bc16630-4e384014.jpg"
>       ],
>       "core_findings": [
>         "no focal consolidation pleural effusion pneumothorax",
>         "Bilateral nodular opacities nipple shadows",
>         "cardiomediastinal silhouette normal",
>         "Clips left lung breast",
>         "upper abdomen unremarkable",
>         "Chronic deformity posterior left sixth seventh ribs"
>       ]
>     },
> 
> 
> 
> # 下面的这个是测试集的某一个
> {
>       "id": "d122eb74-bc404dd2-45a05cd3-18505b72-5058fbdd",
>       "study_id": 59381316,
>       "subject_id": 19991135,
>       "report": "PA and lateral chest views were obtained with patient in upright  position .   Comparison is made with the next preceding similar study obtained  four hours earlier during the same day .   The previously described right-sided  chest tube remains in unchanged position .   No pneumothorax has developed and  there is no evidence of significantly increased pleural densities during this  interval .   The right-sided chest wall emphysema described earlier has  regressed .   No new abnormalities are seen .   Left-sided hemithorax is  unremarkable . ",
>       "image_path": [
>         "p19/p19991135/s59381316/d122eb74-bc404dd2-45a05cd3-18505b72-5058fbdd.jpg"
>       ],
>       "core_findings": []
>     }
> ```
> 
> 然后，在文件`datasets_two_step.py`中，
> 
> ```python
> class PretrainBaseDataset(Dataset):  # finetune and inference phase
>     def __init__(self, args, tokenizer, split, transform=None):
>         self.image_dir = args['image_dir']
>         self.transform = transform
>         self.tokenizer = tokenizer
>         ann = json.loads(open(args['ann_path'], 'r').read())
>         ann = ann[split]
>         self.examples = []
>         self.max_seq_length = args['max_seq_len']
>         if args['align_type'] == 'keywords':
>             for i in range(len(ann)):
>                 if len(ann[i]['core_findings']) == 0:  # 这个跳过了
>                     continue
>                 core_findings = ann[i]['core_findings']
>                 if args['tokenizer_type'] == 'uncased':
>                     core_findings = list(map(lambda x: str(x).lower(), core_findings))
>                 if args['data_name'] == 'mimic_cxr':
>                     item_id = '_'.join([str(ann[i]['subject_id']), str(ann[i]['study_id']), ann[i]['id']])
>                 else:
>                     item_id = ann[i]['id']
>                 self.examples.append({
>                     # "report": report.strip(),
>                     'image_path': ann[i]['image_path'],
>                     'radgraph': ' [SEP] '.join(core_findings),
>                     'id': item_id
>                 })
>         ...........
> 
> 
>     def __len__(self):
>         return len(self.examples)
> ```
> 
> 是我前面的生成不对吗？

可能是提取的方法（或者某些字典的key对没有对应上）不对，而且您的train_data才288。您可以使用我们提取的报告，获取方式如下：
[Google Drive](https://drive.google.com/file/d/1iWdFINSAJ7F97I4rTGddIziJAb-1sL3l/view?usp=drive_link).

**Comment by mk-runner** [comment]
> 我配置的 conda 环境，是您提供的那个，应该是没有什么问题的。 我又重新运行了**两次** `knowledge_encoder/factual_serialization.py`文件，这次，在运行`bash pretrain_mimic_cxr.sh`时，出现的是：
> 
> ```
> train_data is 269239, val_data is 0, test_data is 0
> 
> 
> Some weights of BertModel were not initialized from the model checkpoint at /home/deng/Desktop/FSE/checkpoints/scibert_scivocab_uncased and are newly initialized because the shapes did not match:
> - bert.embeddings.word_embeddings.weight: found shape torch.Size([31090, 768]) in the checkpoint and torch.Size([9841, 768]) in the model instantiated
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> finish instantiate model!, Trainable parameters: 148.270656M
> start pretrain!
> Epoch 1, step 0/8414, itc instance loss: 3.457, itc region loss: 4.078, all_loss: 7.535, lr: 5e-05
> Epoch 1, step 1000/8414, itc instance loss: 2.698, itc region loss: 3.558, all_loss: 6.256, lr: 5e-05
> Epoch 1, step 2000/8414, itc instance loss: 3.218, itc region loss: 3.625, all_loss: 6.843, lr: 5e-05
> Epoch 1, step 3000/8414, itc instance loss: 2.838, itc region loss: 2.816, all_loss: 5.654, lr: 5e-05
> Epoch 1, step 4000/8414, itc instance loss: 2.799, itc region loss: 2.925, all_loss: 5.724, lr: 5e-05
> Epoch 1, step 5000/8414, itc instance loss: 3.264, itc region loss: 2.646, all_loss: 5.911, lr: 5e-05
> Epoch 1, step 6000/8414, itc instance loss: 2.855, itc region loss: 3.199, all_loss: 6.054, lr: 5e-05
> Epoch 1, step 7000/8414, itc instance loss: 2.491, itc region loss: 2.732, all_loss: 5.224, lr: 5e-05
> Epoch 1, step 8000/8414, itc instance loss: 2.839, itc region loss: 2.509, all_loss: 5.348, lr: 5e-05
> Epoch 1, step 8413/8414, itc instance loss: 2.457, itc region loss: 2.716, all_loss: 5.173, lr: 5e-05
> Epoch 1, all train_loss: 5.891088151410381, lr: 5e-05
> Traceback (most recent call last):
>   File "/home/deng/Desktop/FSE/main_finetune.py", line 223, in <module>
>     main()
>   File "/home/deng/Desktop/FSE/main_finetune.py", line 201, in main
>     trainer.train()
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 68, in train
>     result = self._train_epoch(epoch)
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in _train_epoch
>     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in <dictcomp>
>     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
> ZeroDivisionError: float division by zero
> ```
> 
> 为什么在`mimic_cxr_annotation_sen.json`文件中，`test`、`val`部分，生成的`core_findings` 是空列表呢？

在运行时，判断一下`temp_dygie_input.json`，这个文件是否将annotation.json中基本上99%的study都存储在该文件里面。RadGraph是基于该文件的内容，再提取对应的实体和关系，然后structural entities approach进一步处理RadGraph的输出结果。

**Comment by mk-runner** [comment]
从你的提取结果来看，RadGraph环境是没有问题了。很有可能，生成`temp_dygie_input.json`该文件是，有问题。

**Comment by deng1604** [comment]
好吧，我试试你给的文件。但是`temp_dygie_input.json`这个文件，不是自动生成的嘛

**Comment by mk-runner** [comment]
> 好吧，我试试你给的文件。但是`temp_dygie_input.json`这个文件，不是自动生成的嘛

谢谢，在line 84 and line 85，我使用了`del ann['val']; del ann['test']`，所以没有测试集和验证集的结果。但我还不清楚，为什么您的train_data是288。

**Comment by deng1604** [comment]
> 我配置的 conda 环境，是您提供的那个，应该是没有什么问题的。 我又重新运行了**两次** `knowledge_encoder/factual_serialization.py`文件，这次，在运行`bash pretrain_mimic_cxr.sh`时，出现的是：
> 
> ```
> train_data is 269239, val_data is 0, test_data is 0
> 
> 
> Some weights of BertModel were not initialized from the model checkpoint at /home/deng/Desktop/FSE/checkpoints/scibert_scivocab_uncased and are newly initialized because the shapes did not match:
> - bert.embeddings.word_embeddings.weight: found shape torch.Size([31090, 768]) in the checkpoint and torch.Size([9841, 768]) in the model instantiated
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> finish instantiate model!, Trainable parameters: 148.270656M
> start pretrain!
> Epoch 1, step 0/8414, itc instance loss: 3.457, itc region loss: 4.078, all_loss: 7.535, lr: 5e-05
> Epoch 1, step 1000/8414, itc instance loss: 2.698, itc region loss: 3.558, all_loss: 6.256, lr: 5e-05
> Epoch 1, step 2000/8414, itc instance loss: 3.218, itc region loss: 3.625, all_loss: 6.843, lr: 5e-05
> Epoch 1, step 3000/8414, itc instance loss: 2.838, itc region loss: 2.816, all_loss: 5.654, lr: 5e-05
> Epoch 1, step 4000/8414, itc instance loss: 2.799, itc region loss: 2.925, all_loss: 5.724, lr: 5e-05
> Epoch 1, step 5000/8414, itc instance loss: 3.264, itc region loss: 2.646, all_loss: 5.911, lr: 5e-05
> Epoch 1, step 6000/8414, itc instance loss: 2.855, itc region loss: 3.199, all_loss: 6.054, lr: 5e-05
> Epoch 1, step 7000/8414, itc instance loss: 2.491, itc region loss: 2.732, all_loss: 5.224, lr: 5e-05
> Epoch 1, step 8000/8414, itc instance loss: 2.839, itc region loss: 2.509, all_loss: 5.348, lr: 5e-05
> Epoch 1, step 8413/8414, itc instance loss: 2.457, itc region loss: 2.716, all_loss: 5.173, lr: 5e-05
> Epoch 1, all train_loss: 5.891088151410381, lr: 5e-05
> Traceback (most recent call last):
>   File "/home/deng/Desktop/FSE/main_finetune.py", line 223, in <module>
>     main()
>   File "/home/deng/Desktop/FSE/main_finetune.py", line 201, in main
>     trainer.train()
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 68, in train
>     result = self._train_epoch(epoch)
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in _train_epoch
>     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
>   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in <dictcomp>
>     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
> ZeroDivisionError: float division by zero
> ```
> 
> 为什么在`mimic_cxr_annotation_sen.json`文件中，`test`、`val`部分，生成的`core_findings` 是空列表呢？






我后面试的两次，都是这样的：
train_data is 269239, val_data is 0, test_data is 0

第一次可能是没有弄完。

是不是你把这个`del ann['val']; del ann['test']`删了的原因：
```python
    def get_mimic_temp_dygie_input(self, ann_path):
        # note that only the training corpus can be used.
        ann = json.load(open(ann_path))
        print("initialization the input data")
        del ann['val']
        del ann['test']

        ......
```
那是不是，我把这两行删掉就可以了？
```python
        del ann['val']
        del ann['test']
```
另外，为什么您给出的`knowledge_encoder/factual_serialization.py`的代码，要删掉这两个的值呢？
删掉了，这个代码，就跑不通了啊😂

**Comment by mk-runner** [comment]
> > 我配置的 conda 环境，是您提供的那个，应该是没有什么问题的。 我又重新运行了**两次** `knowledge_encoder/factual_serialization.py`文件，这次，在运行`bash pretrain_mimic_cxr.sh`时，出现的是：
> > ```
> > train_data is 269239, val_data is 0, test_data is 0
> > 
> > 
> > Some weights of BertModel were not initialized from the model checkpoint at /home/deng/Desktop/FSE/checkpoints/scibert_scivocab_uncased and are newly initialized because the shapes did not match:
> > - bert.embeddings.word_embeddings.weight: found shape torch.Size([31090, 768]) in the checkpoint and torch.Size([9841, 768]) in the model instantiated
> > You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> > finish instantiate model!, Trainable parameters: 148.270656M
> > start pretrain!
> > Epoch 1, step 0/8414, itc instance loss: 3.457, itc region loss: 4.078, all_loss: 7.535, lr: 5e-05
> > Epoch 1, step 1000/8414, itc instance loss: 2.698, itc region loss: 3.558, all_loss: 6.256, lr: 5e-05
> > Epoch 1, step 2000/8414, itc instance loss: 3.218, itc region loss: 3.625, all_loss: 6.843, lr: 5e-05
> > Epoch 1, step 3000/8414, itc instance loss: 2.838, itc region loss: 2.816, all_loss: 5.654, lr: 5e-05
> > Epoch 1, step 4000/8414, itc instance loss: 2.799, itc region loss: 2.925, all_loss: 5.724, lr: 5e-05
> > Epoch 1, step 5000/8414, itc instance loss: 3.264, itc region loss: 2.646, all_loss: 5.911, lr: 5e-05
> > Epoch 1, step 6000/8414, itc instance loss: 2.855, itc region loss: 3.199, all_loss: 6.054, lr: 5e-05
> > Epoch 1, step 7000/8414, itc instance loss: 2.491, itc region loss: 2.732, all_loss: 5.224, lr: 5e-05
> > Epoch 1, step 8000/8414, itc instance loss: 2.839, itc region loss: 2.509, all_loss: 5.348, lr: 5e-05
> > Epoch 1, step 8413/8414, itc instance loss: 2.457, itc region loss: 2.716, all_loss: 5.173, lr: 5e-05
> > Epoch 1, all train_loss: 5.891088151410381, lr: 5e-05
> > Traceback (most recent call last):
> >   File "/home/deng/Desktop/FSE/main_finetune.py", line 223, in <module>
> >     main()
> >   File "/home/deng/Desktop/FSE/main_finetune.py", line 201, in main
> >     trainer.train()
> >   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 68, in train
> >     result = self._train_epoch(epoch)
> >   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in _train_epoch
> >     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
> >   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in <dictcomp>
> >     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
> > ZeroDivisionError: float division by zero
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 为什么在`mimic_cxr_annotation_sen.json`文件中，`test`、`val`部分，生成的`core_findings` 是空列表呢？
> 
> 我后面试的两次，都是这样的： train_data is 269239, val_data is 0, test_data is 0
> 
> 第一次可能是没有弄完。
> 
> 是不是你把这个`del ann['val']; del ann['test']`删了的原因：
> 
> ```python
>     def get_mimic_temp_dygie_input(self, ann_path):
>         # note that only the training corpus can be used.
>         ann = json.load(open(ann_path))
>         print("initialization the input data")
>         del ann['val']
>         del ann['test']
> 
>         ......
> ```
> 
> 那是不是，我把这两行删掉就可以了？
> 
> ```python
>         del ann['val']
>         del ann['test']
> ```
> 
> 另外，为什么您给出的`knowledge_encoder/factual_serialization.py`的代码，要删掉这两个的值呢？ 删掉了，这个代码，就跑不通了啊😂

对的，仅需要删除`del ann['val']; del ann['test']`，即可。

因为，某个实验，我仅需要train的提取结果，所以删除了val and test。

我这里能正常运行的，不知道您报的啥错误。不能获得temp_dygie_output.json？如果是的，您是不是指定了`is_get_output=False`？     

如果不需要重新保存temp_dygie_input.json文件，将`is_get_output=False`，同时将line 78的代码，放在if作用域外面

**Comment by mk-runner** [comment]
因为，我仅需要train的提取结果，所以删掉了val和test

> > 我配置的 conda 环境，是您提供的那个，应该是没有什么问题的。 我又重新运行了**两次** `knowledge_encoder/factual_serialization.py`文件，这次，在运行`bash pretrain_mimic_cxr.sh`时，出现的是：
> > ```
> > train_data is 269239, val_data is 0, test_data is 0
> > 
> > 
> > Some weights of BertModel were not initialized from the model checkpoint at /home/deng/Desktop/FSE/checkpoints/scibert_scivocab_uncased and are newly initialized because the shapes did not match:
> > - bert.embeddings.word_embeddings.weight: found shape torch.Size([31090, 768]) in the checkpoint and torch.Size([9841, 768]) in the model instantiated
> > You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> > finish instantiate model!, Trainable parameters: 148.270656M
> > start pretrain!
> > Epoch 1, step 0/8414, itc instance loss: 3.457, itc region loss: 4.078, all_loss: 7.535, lr: 5e-05
> > Epoch 1, step 1000/8414, itc instance loss: 2.698, itc region loss: 3.558, all_loss: 6.256, lr: 5e-05
> > Epoch 1, step 2000/8414, itc instance loss: 3.218, itc region loss: 3.625, all_loss: 6.843, lr: 5e-05
> > Epoch 1, step 3000/8414, itc instance loss: 2.838, itc region loss: 2.816, all_loss: 5.654, lr: 5e-05
> > Epoch 1, step 4000/8414, itc instance loss: 2.799, itc region loss: 2.925, all_loss: 5.724, lr: 5e-05
> > Epoch 1, step 5000/8414, itc instance loss: 3.264, itc region loss: 2.646, all_loss: 5.911, lr: 5e-05
> > Epoch 1, step 6000/8414, itc instance loss: 2.855, itc region loss: 3.199, all_loss: 6.054, lr: 5e-05
> > Epoch 1, step 7000/8414, itc instance loss: 2.491, itc region loss: 2.732, all_loss: 5.224, lr: 5e-05
> > Epoch 1, step 8000/8414, itc instance loss: 2.839, itc region loss: 2.509, all_loss: 5.348, lr: 5e-05
> > Epoch 1, step 8413/8414, itc instance loss: 2.457, itc region loss: 2.716, all_loss: 5.173, lr: 5e-05
> > Epoch 1, all train_loss: 5.891088151410381, lr: 5e-05
> > Traceback (most recent call last):
> >   File "/home/deng/Desktop/FSE/main_finetune.py", line 223, in <module>
> >     main()
> >   File "/home/deng/Desktop/FSE/main_finetune.py", line 201, in main
> >     trainer.train()
> >   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 68, in train
> >     result = self._train_epoch(epoch)
> >   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in _train_epoch
> >     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
> >   File "/home/deng/Desktop/FSE/modules/trainer_finetune_iu.py", line 299, in <dictcomp>
> >     val_ret = {k: v / len(self.val_dataloader) for k, v in val_ret.items()}
> > ZeroDivisionError: float division by zero
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 为什么在`mimic_cxr_annotation_sen.json`文件中，`test`、`val`部分，生成的`core_findings` 是空列表呢？
> 
> 我后面试的两次，都是这样的： train_data is 269239, val_data is 0, test_data is 0
> 
> 第一次可能是没有弄完。
> 
> 是不是你把这个`del ann['val']; del ann['test']`删了的原因：
> 
> ```python
>     def get_mimic_temp_dygie_input(self, ann_path):
>         # note that only the training corpus can be used.
>         ann = json.load(open(ann_path))
>         print("initialization the input data")
>         del ann['val']
>         del ann['test']
> 
>         ......
> ```
> 
> 那是不是，我把这两行删掉就可以了？
> 
> ```python
>         del ann['val']
>         del ann['test']
> ```
> 
> 另外，为什么您给出的`knowledge_encoder/factual_serialization.py`的代码，要删掉这两个的值呢？ 删掉了，这个代码，就跑不通了啊😂
